name: Validate and lint

on:
  pull_request:
    branches:
      - main

jobs:
  terraform_validation:
    strategy:
      matrix:
        version: ["1.11", latest]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.version }}

      - name: Terraform init
        run: "terraform init || terraform init -upgrade"

      - name: Terraform validate
        run: "terraform validate"

      - name: Terraform fmt
        run: |
          terraform fmt
          if [ -n "$(git status --porcelain)" ]; then
            echo "ERROR: terraform fmt resulted in changes. Run 'terraform fmt' locally and append the changes."
            echo
            git diff
            echo
            git status
            exit 1
          fi

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform init
        run: terraform init

      - name: Setup terraform-docs
        run: |
          curl -sSLo terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz terraform-docs
          sudo mv terraform-docs /usr/local/bin/
          terraform-docs --version

      - name: Check docs are up to date
        run: |
          make generate-doc
          git diff README.md
          if [ -n "$(git status --porcelain README.md)" ]; then
            echo "ERROR: README.md is out of date. Run 'make generate-doc' locally and commit the changes."
            exit 1
          fi
          echo "README.md is up to date."

  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Cache plugin dir
        uses: actions/cache@v5
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.60.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact
